# Generated by Django 2.1.3 on 2018-11-11 11:55

from django.db import migrations, models
import django.db.models.deletion
import watch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(default=-1)),
                ('episode_name', models.CharField(blank=True, max_length=250)),
                ('episode_raw_name', models.CharField(blank=True, max_length=250)),
                ('video_src', models.CharField(max_length=250)),
                ('folder_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('movie_raw_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('release_year', models.IntegerField(blank=True, default=0)),
                ('imdb_scor', models.DecimalField(decimal_places=2, default=10, max_digits=3)),
                ('genres', models.CharField(blank=True, max_length=250)),
                ('trailer_src', models.CharField(blank=True, max_length=250)),
                ('img', models.CharField(default=watch.models.Movie.noImageSrc, max_length=250)),
                ('folder_id', models.CharField(blank=True, max_length=50)),
                ('video_src', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(blank=True, max_length=250)),
                ('season_number', models.IntegerField(default=-1)),
                ('season_scraped_from', models.CharField(blank=True, max_length=250)),
                ('img', models.CharField(default=watch.models.Season.noImageSrc, max_length=250)),
                ('folder_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('release_year', models.IntegerField(blank=True, default=0)),
                ('finish_year', models.IntegerField(blank=True, default=0)),
                ('imdb_scor', models.DecimalField(decimal_places=2, default=10, max_digits=3)),
                ('genres', models.CharField(blank=True, max_length=250)),
                ('trailer_src', models.CharField(blank=True, max_length=250)),
                ('img', models.CharField(default=watch.models.Serie.noImageSrc, max_length=250)),
                ('folder_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Series_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=512)),
                ('episode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Episode')),
                ('season', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Season')),
                ('series', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Serie')),
            ],
        ),
        migrations.AddIndex(
            model_name='serie',
            index=models.Index(fields=['series_name'], name='watch_serie_series__e67455_idx'),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.Serie'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['movie_name'], name='watch_movie_movie_n_d3d084_idx'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.Season'),
        ),
        migrations.AddIndex(
            model_name='series_detail',
            index=models.Index(fields=['key'], name='watch_serie_key_5525d3_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['series', 'season_number'], name='watch_seaso_series__bb17e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'season_number')},
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'episode_number'], name='watch_episo_season__8d9605_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_number')},
        ),
    ]
