# Generated by Django 2.1.3 on 2018-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_host',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_host',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
