# Generated by Django 2.0.7 on 2018-08-16 20:38

from django.db import migrations, models
import django.db.models.deletion
import series.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(default=-1)),
                ('episode_name', models.CharField(blank=True, max_length=250)),
                ('video_src', models.CharField(max_length=250)),
                ('folder_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(blank=True, max_length=250)),
                ('season_number', models.IntegerField(default=-1)),
                ('season_scraped_from', models.CharField(blank=True, max_length=250)),
                ('img', models.CharField(default=series.models.Season.noImageSrc, max_length=250)),
                ('folder_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('imdb_scor', models.IntegerField(default=10)),
                ('genres', models.CharField(blank=True, max_length=250)),
                ('trailer_src', models.CharField(blank=True, max_length=250)),
                ('img', models.CharField(default=series.models.Series.noImageSrc, max_length=250)),
                ('folder_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['series_name'], name='series_seri_series__7d63ec_idx'),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Season'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['series', 'season_number'], name='series_seas_series__ba5a70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'season_number')},
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'episode_number'], name='series_epis_season__c2dd96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_number')},
        ),
    ]
