# Generated by Django 2.0.7 on 2018-08-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_episode_episode_raw_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=512)),
                ('episode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='series.Episode')),
                ('season', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='series.Season')),
            ],
        ),
        migrations.AlterField(
            model_name='series',
            name='imdb_scor',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=3),
        ),
        migrations.AddField(
            model_name='series_detail',
            name='series',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AddIndex(
            model_name='series_detail',
            index=models.Index(fields=['key'], name='series_seri_key_09a530_idx'),
        ),
    ]
