# Generated by Django 2.0.7 on 2018-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20180818_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='finished_date',
        ),
        migrations.RemoveField(
            model_name='series',
            name='release_date',
        ),
        migrations.AddField(
            model_name='series',
            name='finished_year',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='release_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
