# Generated by Django 2.0.7 on 2018-08-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20180818_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='finished_year',
            new_name='finish_year',
        ),
    ]
